# Generated by Django 5.2.3 on 2025-08-19 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_edicao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
